### ISSUE TITLE
写操作都设了lockDbWrite(c->db)，这样是不是很影响多线程性能

### ISSUE THREAD

**Issue by andyli029** [vipshop/vire#5]
```
int
lockDbWrite(redisDb *db)
{
    pthread_rwlock_wrlock(&db->rwl);
    return VR_OK;
}

```

**Comment by deep011** [comment]
效率还可以，你可以用vire-benchmark测一下set命令

**Comment by andyli029** [comment]
和标准的redis性能比较，有对比性能结果，测试报告嘛？

**Comment by deep011** [comment]
set单个key，vire开四个线程，qps在33万左右，肯定比单线程redis强很多

**Comment by andyli029** [comment]
vire开四个线程肯定要和四个原始redis实例对比
你们一个物理机上是起来几个redis实例，又起来几个vire

**Comment by deep011** [comment]
4线程的vire肯定没有4个redis的总qps高，这个没什么好测的

**Comment by andyli029** [comment]
你们在生产环境上一个物理机是起几个redis实例，又起来几个vire

**Comment by yjhjstz** [comment]
@andyli029 @deep011 多线程 VS 多实例的考量, 多线程的 Vire 究竟在生产中比多实例的 redis 节省了多少机器？
是否现在已经使用了pika, 我看 https://github.com/Qihoo360/pika 有 vipshop 的logo。
